// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails application backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fs$0 from "../io/fs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sieve$0 from "./sieve/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function CreateVault() {
    return $Call.ByID(3368601999);
}

/**
 * @param {string} uuid
 * @param {string} storeRelPath
 * @param {string} blkId
 * @returns {$CancellablePromise<sieve$0.ImageDesc>}
 */
export function DescribeImage(uuid, storeRelPath, blkId) {
    return $Call.ByID(1495264349, uuid, storeRelPath, blkId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} uuid
 * @param {string} targetURL
 * @param {string} id
 * @returns {$CancellablePromise<$models.AssetDTO>}
 */
export function DownloadAsset(uuid, targetURL, id) {
    return $Call.ByID(4063308287, uuid, targetURL, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function GetLinkTitle(url) {
    return $Call.ByID(4215305843, url);
}

/**
 * @returns {$CancellablePromise<$models.StoreInfo>}
 */
export function GetStoreInfo() {
    return $Call.ByID(3487247924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetStorePath() {
    return $Call.ByID(651980287);
}

/**
 * @returns {$CancellablePromise<fs$0.FS>}
 */
export function GetThemesFS() {
    return $Call.ByID(1139965578);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function InitVault(path) {
    return $Call.ByID(372540493, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function RefineLanguage(content) {
    return $Call.ByID(4233781034, content);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectVault() {
    return $Call.ByID(1787067759);
}

/**
 * SetApp wires up the Wails application and window references after creation.
 * @param {application$0.App | null} app
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app, window) {
    return $Call.ByID(4256893662, app, window);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ShowInFiles(path) {
    return $Call.ByID(2000255538, path);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ShowInFilesByID(id) {
    return $Call.ByID(1821721222, id);
}

// Private type creation functions
const $$createType0 = sieve$0.ImageDesc.createFrom;
const $$createType1 = $models.AssetDTO.createFrom;
const $$createType2 = $models.StoreInfo.createFrom;
