// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sieve$0 from "./sieve/models.js";

/**
 * AssetDTO carries the ExternalRef the frontend inserts directly into markdown.
 */
export class AssetDTO {
    /**
     * Creates a new AssetDTO instance.
     * @param {Partial<AssetDTO>} [$$source = {}] - The source object to create the AssetDTO.
     */
    constructor($$source = {}) {
        if (!("externalRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["externalRef"] = "";
        }
        if (!("encoding" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["encoding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetDTO(/** @type {Partial<AssetDTO>} */($$parsedSource));
    }
}

export class StoreInfo {
    /**
     * Creates a new StoreInfo instance.
     * @param {Partial<StoreInfo>} [$$source = {}] - The source object to create the StoreInfo.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("buffersPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buffersPath"] = "";
        }
        if (!("notesPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notesPath"] = "";
        }
        if (!("isNew" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isNew"] = false;
        }
        if (!("tier" in $$source)) {
            /**
             * @member
             * @type {sieve$0.Tier}
             */
            this["tier"] = sieve$0.Tier.$zero;
        }
        if (!("cli" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cli"] = "";
        }
        if (!("debug" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["debug"] = false;
        }
        if (!("autosaveDebounce" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autosaveDebounce"] = 0;
        }
        if (!("themeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeName"] = "";
        }
        if (!("themeVars" in $$source)) {
            /**
             * @member
             * @type {sieve$0.ThemeVars}
             */
            this["themeVars"] = {};
        }
        if (!("maxHistoryVersions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxHistoryVersions"] = 0;
        }
        if (!("cliTimeoutLong" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cliTimeoutLong"] = 0;
        }
        if (!("showPrompts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showPrompts"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoreInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StoreInfo}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("themeVars" in $$parsedSource) {
            $$parsedSource["themeVars"] = $$createField10_0($$parsedSource["themeVars"]);
        }
        return new StoreInfo(/** @type {Partial<StoreInfo>} */($$parsedSource));
    }
}

// Private type creation functions
var $$createType0 = /** @type {(...args: any[]) => any} */(function $$initCreateType0(...args) {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType1;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
