// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    ImageDesc,
    Tier
} from "./models.js";

import * as $models from "./models.js";

/**
 * ThemeVars holds the raw key→value colour/font properties loaded from a theme
 * JSON file. Each key becomes a --theme-<key> CSS Custom Property.
 * @typedef {$models.ThemeVars} ThemeVars
 */
