// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ImageDesc is the structured response from AIService.DescribeImage.
 */
export class ImageDesc {
    /**
     * Creates a new ImageDesc instance.
     * @param {Partial<ImageDesc>} [$$source = {}] - The source object to create the ImageDesc.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("alt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alt"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detect"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageDesc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageDesc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageDesc(/** @type {Partial<ImageDesc>} */($$parsedSource));
    }
}

/**
 * ThemeVars holds the raw key→value colour/font properties loaded from a theme
 * JSON file. Each key becomes a --theme-<key> CSS Custom Property.
 * @typedef {{ [_ in string]?: string }} ThemeVars
 */

/**
 * Tier represents the capability level of the app based on CLI availability.
 * @readonly
 * @enum {number}
 */
export const Tier = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * no CLI configured or not on PATH
     */
    TierDumb: 1,

    /**
     * CLI configured and available
     */
    TierSmart: 2,
};
