// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVault() {
  return window['go']['main']['App']['CreateVault']();
}

export function DescribeImage(arg1) {
  return window['go']['main']['App']['DescribeImage'](arg1);
}

export function DownloadAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadAsset'](arg1, arg2, arg3);
}

export function GetStoreInfo() {
  return window['go']['main']['App']['GetStoreInfo']();
}

export function GetStorePath() {
  return window['go']['main']['App']['GetStorePath']();
}

export function GetThemesFS() {
  return window['go']['main']['App']['GetThemesFS']();
}

export function InitVault(arg1) {
  return window['go']['main']['App']['InitVault'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefineLanguage(arg1) {
  return window['go']['main']['App']['RefineLanguage'](arg1);
}

export function SelectVault() {
  return window['go']['main']['App']['SelectVault']();
}

export function ShowInFiles(arg1) {
  return window['go']['main']['App']['ShowInFiles'](arg1);
}

export function ShowInFilesByID(arg1) {
  return window['go']['main']['App']['ShowInFilesByID'](arg1);
}
