package requesthandlers

import (
	"encoding/json"
	"html/template"
	"net/http"

	"sieve/logger"

	"github.com/go-chi/chi/v5"
)

type HelpHandler struct {
	Tmpl    *template.Template
	Version string // release version shown in the footer
	Credits []byte // embedded third-party-licenses.json (generated by tools/gencredits)
}

// CreditEntry mirrors one entry of the generated third-party-licenses.json.
type CreditEntry struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	License   string `json:"license"`
	Copyright string `json:"copyright"`
	Source    string `json:"source"`
	Note      string `json:"note"`
	Text      string `json:"text"`
}

func (h *HelpHandler) RegisterPaths(r chi.Router) {
	r.Get("/ui/views/help", h.handleHelp)
	r.Get("/ui/views/licenses", h.handleLicenses)
}

func (h *HelpHandler) handleHelp(w http.ResponseWriter, r *http.Request) {
	h.render(w, "help.html", struct{ Version string }{h.Version})
}

func (h *HelpHandler) handleLicenses(w http.ResponseWriter, r *http.Request) {
	h.render(w, "licenses.html", struct {
		Version string
		Credits []CreditEntry
	}{h.Version, h.creditEntries()})
}

func (h *HelpHandler) render(w http.ResponseWriter, name string, data any) {
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := h.Tmpl.ExecuteTemplate(w, name, data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// creditEntries parses the embedded credits artifact; a parse failure logs and
// renders the help dialog without the licenses section rather than erroring.
func (h *HelpHandler) creditEntries() []CreditEntry {
	var artifact struct {
		Entries []CreditEntry `json:"entries"`
	}
	if err := json.Unmarshal(h.Credits, &artifact); err != nil {
		logger.Error("help: failed to parse embedded third-party credits", "err", err)
		return nil
	}
	return artifact.Entries
}
