package requesthandlers

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"sieve/logger"
	"sieve/sieve"
	"sieve/store"
)

type InternalizeHandler struct {
	ServiceProvider *sieve.ServiceProvider
	Broadcast       func(event, data string)
}

func (h *InternalizeHandler) RegisterPaths(r chi.Router) {
	r.Post("/api/internalize", h.handleInternalize)
}

type internalizeRequest struct {
	UUID       string `json:"uuid"`
	Source     string `json:"source"`
	Mode       string `json:"mode"`
	ID         string `json:"id"`         // block ID generated by frontend; must be present
	Body       string `json:"body"`       // markdown body including the PENDING web-clip block
	DocContent string `json:"docContent"` // document body BEFORE the PENDING block was inserted (for Summarise context)
}

func (h *InternalizeHandler) handleInternalize(w http.ResponseWriter, r *http.Request) {
	var req internalizeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request", http.StatusBadRequest)
		return
	}

	if req.UUID == "" || req.Source == "" || req.ID == "" {
		http.Error(w, "uuid, source, and id are required", http.StatusBadRequest)
		return
	}
	if req.Mode != "fetch" && req.Mode != "summarise" {
		req.Mode = "fetch"
	}

	// Save body with PENDING block before AI runs (same pattern as handleAiAsk).
	if req.Body != "" {
		for attempt := 0; attempt < 3; attempt++ {
			doc, err := h.ServiceProvider.Documents.LoadByUUID(req.UUID)
			if err != nil {
				logger.Error("handleInternalize: load for pre-save failed", "err", err)
				break
			}
			doc.SetBody([]byte(req.Body))
			if _, err := h.ServiceProvider.Documents.Save(doc); err != nil {
				if errors.Is(err, store.ErrStaleStorable) {
					continue
				}
				logger.Error("handleInternalize: save body failed", "err", err)
			}
			break
		}
	}

	w.WriteHeader(http.StatusOK)

	go h.runInBackground(req.UUID, req.ID, req.Source, req.Mode, req.DocContent)
}

func (h *InternalizeHandler) runInBackground(uuid, id, source, mode, docContent string) {
	settings := h.ServiceProvider.State.LoadSettings()
	model := settings.Model

	title, content, cliErr := h.ServiceProvider.AI.RunWebClip(uuid, id, source, mode, docContent)

	var status, errMsg, completedAt string
	if cliErr != nil {
		if strings.Contains(cliErr.Error(), "timeout") {
			status = "TIMEOUT"
		} else {
			status = "ERROR"
			errMsg = "Claude could not retrieve this page. Check that your MCP configuration can access this URL."
			model = ""
		}
		title = ""
		content = ""
	} else {
		status = "COMPLETE"
		completedAt = time.Now().UTC().Format(time.RFC3339)
	}

	if err := h.ServiceProvider.AI.ResolveWebClip(uuid, id, title, content, model, errMsg, status, completedAt); err != nil {
		logger.Error("handleInternalize: ResolveWebClip failed", "id", id, "err", err)
	}

	payload, _ := json.Marshal(map[string]string{
		"uuid":        uuid,
		"blkId":       id,
		"status":      status,
		"title":       title,
		"content":     content,
		"model":       model,
		"completedAt": completedAt,
		"error":       errMsg,
	})
	if h.Broadcast != nil {
		h.Broadcast("ai:web-clip-resolved", string(payload))
	}
}
