// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * An FS provides access to a hierarchical file system.
 * 
 * The FS interface is the minimum implementation required of the file system.
 * A file system may implement additional interfaces,
 * such as [ReadFileFS], to provide additional or optimized functionality.
 * 
 * [testing/fstest.TestFS] may be used to test implementations of an FS for
 * correctness.
 * @typedef {any} FS
 */
