// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stash} from '../models';
import {main} from '../models';
import {fs} from '../models';

export function Ask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<string>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateVault():Promise<string>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DescribeImage(arg1:string):Promise<stash.ImageDesc>;

export function DiscardBuffer(arg1:string):Promise<void>;

export function DownloadAsset(arg1:string,arg2:string,arg3:string):Promise<main.AssetDTO>;

export function EvaluateBuffer(arg1:string):Promise<stash.FilingRecommendation>;

export function Explain(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function FileBuffer(arg1:string):Promise<main.NoteDTO>;

export function FileBufferWithName(arg1:string,arg2:string):Promise<main.NoteDTO>;

export function GetDocumentVersion(arg1:string,arg2:main.VersionRefDTO):Promise<main.VersionedStorableDTO>;

export function GetNotes():Promise<Array<stash.NoteEntry>>;

export function GetPrompts():Promise<Array<stash.PromptEntry>>;

export function GetSession():Promise<stash.Session>;

export function GetStoreInfo():Promise<main.StoreInfo>;

export function GetStorePath():Promise<string>;

export function GetThemesFS():Promise<fs.FS>;

export function InitVault(arg1:string):Promise<void>;

export function LoadBuffer(arg1:string):Promise<any>;

export function LoadPrompt(arg1:string):Promise<string>;

export function LoadSettings():Promise<stash.Settings>;

export function MoveNote(arg1:string,arg2:string):Promise<main.NoteDTO>;

export function NewBuffer():Promise<main.BufferDTO>;

export function Quit():Promise<void>;

export function RefileNote(arg1:main.BufferDTO):Promise<main.NoteDTO>;

export function RefineLanguage(arg1:string):Promise<string>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function SaveAsset(arg1:string,arg2:string,arg3:string):Promise<main.AssetDTO>;

export function SaveBuffer(arg1:main.BufferDTO):Promise<any>;

export function SaveMetaWidth(arg1:number):Promise<void>;

export function SavePrompt(arg1:string,arg2:string):Promise<string>;

export function SavePromptsHeight(arg1:number):Promise<void>;

export function SaveSession(arg1:stash.Session):Promise<void>;

export function SaveSettings(arg1:stash.Settings):Promise<void>;

export function SaveSidebarWidth(arg1:number):Promise<void>;

export function SearchStore(arg1:string):Promise<Array<stash.SearchResult>>;

export function SelectVault():Promise<string>;

export function ShowInFiles(arg1:string):Promise<void>;

export function TogglePrompts():Promise<boolean>;
