// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVault():Promise<string>;

export function GetActiveUUID():Promise<string>;

export function InitVault(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function Quit():Promise<void>;

export function SelectVault():Promise<string>;

export function ShowInFilesByID(arg1:string):Promise<void>;

export function SwitchLibrary(arg1:string):Promise<string>;
