// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Ask'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateVault() {
  return window['go']['main']['App']['CreateVault']();
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DescribeImage(arg1) {
  return window['go']['main']['App']['DescribeImage'](arg1);
}

export function DiscardBuffer(arg1) {
  return window['go']['main']['App']['DiscardBuffer'](arg1);
}

export function DownloadAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadAsset'](arg1, arg2, arg3);
}

export function EvaluateBuffer(arg1) {
  return window['go']['main']['App']['EvaluateBuffer'](arg1);
}

export function Explain(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Explain'](arg1, arg2, arg3, arg4);
}

export function FileBuffer(arg1) {
  return window['go']['main']['App']['FileBuffer'](arg1);
}

export function FileBufferWithName(arg1, arg2) {
  return window['go']['main']['App']['FileBufferWithName'](arg1, arg2);
}

export function GetDocumentVersion(arg1, arg2) {
  return window['go']['main']['App']['GetDocumentVersion'](arg1, arg2);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPrompts() {
  return window['go']['main']['App']['GetPrompts']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetStoreInfo() {
  return window['go']['main']['App']['GetStoreInfo']();
}

export function GetStorePath() {
  return window['go']['main']['App']['GetStorePath']();
}

export function GetThemesFS() {
  return window['go']['main']['App']['GetThemesFS']();
}

export function InitVault(arg1) {
  return window['go']['main']['App']['InitVault'](arg1);
}

export function LoadBuffer(arg1) {
  return window['go']['main']['App']['LoadBuffer'](arg1);
}

export function LoadPrompt(arg1) {
  return window['go']['main']['App']['LoadPrompt'](arg1);
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function RefileNote(arg1) {
  return window['go']['main']['App']['RefileNote'](arg1);
}

export function NewBuffer() {
  return window['go']['main']['App']['NewBuffer']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefileNote(arg1) {
  return window['go']['main']['App']['RefileNote'](arg1);
}

export function RefineLanguage(arg1) {
  return window['go']['main']['App']['RefineLanguage'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RestorePrompt(arg1) {
  return window['go']['main']['App']['RestorePrompt'](arg1);
}

export function SaveAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAsset'](arg1, arg2, arg3);
}

export function SaveBuffer(arg1) {
  return window['go']['main']['App']['SaveBuffer'](arg1);
}

export function SaveMetaWidth(arg1) {
  return window['go']['main']['App']['SaveMetaWidth'](arg1);
}

export function SavePrompt(arg1, arg2) {
  return window['go']['main']['App']['SavePrompt'](arg1, arg2);
}

export function SavePromptsHeight(arg1) {
  return window['go']['main']['App']['SavePromptsHeight'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSidebarWidth(arg1) {
  return window['go']['main']['App']['SaveSidebarWidth'](arg1);
}

export function SearchStore(arg1) {
  return window['go']['main']['App']['SearchStore'](arg1);
}

export function SelectVault() {
  return window['go']['main']['App']['SelectVault']();
}

export function SettingsPath() {
  return window['go']['main']['App']['SettingsPath']();
}

export function ShowInFiles(arg1) {
  return window['go']['main']['App']['ShowInFiles'](arg1);
}

export function TogglePrompts() {
  return window['go']['main']['App']['TogglePrompts']();
}
