// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVault() {
  return window['go']['main']['App']['CreateVault']();
}

export function GetActiveUUID() {
  return window['go']['main']['App']['GetActiveUUID']();
}

export function InitVault(arg1) {
  return window['go']['main']['App']['InitVault'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SelectVault() {
  return window['go']['main']['App']['SelectVault']();
}

export function ShowInFilesByID(arg1) {
  return window['go']['main']['App']['ShowInFilesByID'](arg1);
}

export function SwitchLibrary(arg1) {
  return window['go']['main']['App']['SwitchLibrary'](arg1);
}
