// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sieve} from '../models';
import {main} from '../models';
import {fs} from '../models';

export function CreateVault():Promise<string>;

export function DescribeImage(arg1:string,arg2:string,arg3:string):Promise<sieve.ImageDesc>;

export function DownloadAsset(arg1:string,arg2:string,arg3:string):Promise<main.AssetDTO>;

export function GetActiveUUID():Promise<string>;

export function GetLinkTitle(arg1:string):Promise<string>;

export function GetStoreInfo():Promise<main.StoreInfo>;

export function GetStorePath():Promise<string>;

export function GetThemesFS():Promise<fs.FS>;

export function InitVault(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RefineLanguage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectVault():Promise<string>;

export function ShowInFiles(arg1:string):Promise<void>;

export function ShowInFilesByID(arg1:string):Promise<void>;

export function SwitchLibrary(arg1:string):Promise<string>;
